version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/publishing-app

hooks:
  BeforeInstall:
    - location: cicdscripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: cicdscripts/application_start.sh
      timeout: 500
      runas: ubuntu
