import Head from "next/head";
import NavMenu from "../components/Nav";
import PageLayout from '../components/PageLayout';

import styles from '../styles/Home.module.css'
import { Col, Container, Row } from 'react-bootstrap';
import Footer from "../components/Footer";

export default function SelfPublish() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Terms of Use</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavMenu />
      <PageLayout>
        <Container fluid>
          <Container className="container">
            <Row className={styles.heading}>
              <h1>Terms of Use</h1>
            </Row>
          </Container>
        </Container>
        <Container fluid>
          <Container className="container">
            <Row>
              <Col>
                <ol className={styles.orderedlist}>
                  <li>
                    <b>USER OBLIGATIONS.</b> You represent that You are at least the legal age of majority and will, at all times, provide true, accurate and complete information when submitting any information the LSI Site, including, without limitation, when You provide information during registration or on other forms. If You provide any false, inaccurate, or incomplete information, LSI reserves the right to terminate your access immediately to the LSI Site. In addition, You agree to abide by all applicable local, state, national, and international laws and regulations with respect to your use of the LSI Site or notuse this site if any applicable laws forbid its use. Without limiting the generality of the foregoing, You agree that you will not use nor disclose to any other party in a manner not permitted by this TOU any personally identifiable information, which You receive or which is made available from LSI in connection with this TOU. In addition, You also acknowledge and agree that use of the internet and access to or transmissions or communications with the LSI Site is solely at Your own risk. While LSI has endeavored to create a secure and reliable LSI Site, you should understand that the confidentiality of any communication or material transmitted to or from the LSI Site over the Internet or other form of global communication network cannot be guaranteed. LSI is not responsible for the security of any information transmitted to or from the LSI Site. You agree to assume all responsibility concerning activities related to Your use of the LSI Site. LSI does not provide You support for the LSI Site.
                  </li>
                  <li>
                    <b>USER NAME.</b> Your account information is accessible through the use of a USERID and PASSWORD assigned and/or controlled by You. You are solely responsible for protecting Your USERID and PASSWORD and hereby agree to accept all responsibility for any activity that occurs under Your account with your USERID and PASSWORD. In addition, should any of Your employees with access to this site leave Your business/institution, you will be responsible for changing any PASSWORDS if you believe such a step is warranted. LSI is not responsible for any liability arising from any unauthorized use of this service (including without limitation from Your business, institution or from Your failure to safeguard a PASSWORD from unauthorized use). Only one Authorized User can use one user name and password and, thus, one account. By using the LSI Site, You agree to consider Your user name and password as confidential information and to keep Your user name and password confidential. You also agree not to use another Authorized User's user name and password. You will immediately notify LSI if You become aware of any loss or theft of Your password or any unauthorized use of Your user name and password. LSI will not be liable for any loss or damage arising from Your failure to comply with these obligations. LSI reserves the right to delete or change a user name or password at any time and for any reason with reasonable notice.
                  </li>
                  <li>
                    <b>LICENSE GRANT.</b> The LSI Site is provided by LSI, and this TOU provides to You a revocable, limited, non-exclusive, non-transferable license to use the LSI Site conditioned on Your continued compliance with the terms and conditions of this TOU and this TOU permits You to use and access for business purposes only the LSI Site. You may also download materials and information from the LSI Site solely for Your internal business use, provided that all hard copies retain all copyright and other applicable notices contained in such materials and information.
                  </li>
                  <li>
                    <b>RESTRICTIONS.</b> This is for limited use only. You may not use, copy, store, reproduce, transmit, distribute, display, rent, lease, sell, modify, alter, license, sublicense, or commercially exploit any data provided by LSI through the LSI Site in any manner unless expressly permitted by this TOU. In addition, You may not modify, translate, decompile, create derivative work(s) of, copy, distribute, disassemble, broadcast, transmit, publish, remove, or alter any proprietary notices or labels. You may not: (i) reproduce or circumvent the navigational structure or presentation of the LSI Site to obtain or attempt to obtain any materials, documents, or information through any means not purposely made available through the LSI Site, (ii) attempt to gain unauthorized access to any portion or feature of the LSI Site, including, without limitation, the account of another Authorized User(s), or any other systems or networks connected to the LSI Site or to any LSI server or to any of the services offered on or through the LSI Site, by hacking, password "mining," or any other illegitimate or prohibited means, (iii) probe, scan, or test the vulnerability of the LSI Site or any network connected to the LSI Site, nor breach the security or authentication measures on the LSI Site or any network connected to the LSI Site, (iv) reverse lookup, trace, or seek to trace any information on any other Authorized User of or visitor to the LSI Site, (v) take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the LSI Site or LSI's systems or networks or any systems or networks connected to the LSI Site, (vi) use any device, software to interfere with the proper working of the LSI Site or any transaction conducted on the LSI Site, or with any other person's use of the LSI Site, (vii) resell, or otherwise permit third parties to access and use the LSI Site (or any part thereof) without LSI prior written permission, or (viii) use the LSI Site in an unlawful manner or in a manner that could damage, disparage, or otherwise negatively impact LSI.
                  </li>
                  <li>
                    <b>USER OBLIGATIONS.</b> You represent that You are at least the legal age of majority and will, at all times, provide true, accurate and complete information when submitting any information the LSI Site, including, without limitation, when You provide information during registration or on other forms. If You provide any false, inaccurate, or incomplete information, LSI reserves the right to terminate your access immediately to the LSI Site. In addition, You agree to abide by all applicable local, state, national, and international laws and regulations with respect to your use of the LSI Site or notuse this site if any applicable laws forbid its use. Without limiting the generality of the foregoing, You agree that you will not use nor disclose to any other party in a manner not permitted by this TOU any personally identifiable information, which You receive or which is made available from LSI in connection with this TOU. In addition, You also acknowledge and agree that use of the internet and access to or transmissions or communications with the LSI Site is solely at Your own risk. While LSI has endeavored to create a secure and reliable LSI Site, you should understand that the confidentiality of any communication or material transmitted to or from the LSI Site over the Internet or other form of global communication network cannot be guaranteed. LSI is not responsible for the security of any information transmitted to or from the LSI Site. You agree to assume all responsibility concerning activities related to Your use of the LSI Site. LSI does not provide You support for the LSI Site.
                  </li>
                  <li>
                    <b>TERM AND TERMINATION.</b> This TOU and Your right to use the LSI Site will take effect at the moment you click "I ACCEPT", and access, or use the LSI Site and is effective until terminated as set forth below. This TOU will terminate automatically if You click "I DECLINE". In addition, LSI reserves the right at any time if You violate any term or condition of this TOU, to deny your access to the LSI Site or to any portion thereof in order to protect its name and goodwill, its business, and/or other Authorized Users. Termination will be effective without notice. You may also terminate this TOU at any time by ceasing to use the LSI Site, but all applicable provisions of this TOU will survive termination. Upon termination, you must destroy all copies of any aspect of the LSI Site in your possession. The provisions concerning LSI's proprietary rights, feedback, indemnity, disclaimers of warranty, limitation of liability, and governing law will survive the termination of this TOU for any reason.
                  </li>
                  <li>
                    <b>PRIVACY POLICY.</b> Please see our Privacy Policy for a summary of personal identifying information collection and use practices.
                  </li>
                  <li>
                    <b>LIABILITY DISCLAIMER.</b> THE INFORMATION, PRODUCTS, AND SERVICES PUBLISHED ON THIS SITE MAY INCLUDE INACCURACIES OR TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY ADDED TO THE INFORMATION HEREIN. LSI AND/OR ITS SUPPLIERS OR AFFILIATES MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF THE INFORMATION, PRODUCTS, AND SERVICES CONTAINED ON THIS SITE FOR ANY PURPOSE. ALL SUCH INFORMATION, PRODUCTS, AND SERVICES ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. LSI, ITS AFFILIATES AND/OR ITS SUPPLIERS HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH REGARD TO THIS INFORMATION, PRODUCTS, AND SERVICES, INCLUDING ALL IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NONINFRINGEMENT. IN NO EVENT SHALL LSI, ITS AFFILIATES AND/OR ITS SUPPLIERS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF THIS SITE OR WITH THE DELAY OR INABILITY TO USE THIS SITE, OR FOR ANY INFORMATION, PRODUCTS, AND SERVICES OBTAINED THROUGH THIS SITE, OR OTHERWISE ARISING OUT OF THE USE OF THIS SITE, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, EVEN IF LSI, ITS AFFILIATES AND/OR ANY OF ITS SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. BECAUSE SOME STATES/JURISDICTIONS HAVE LIMITATIONS ON THE APPLICABILITY OF DISCLAIMERS OR DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. NOTWITHSTANDING THE FOREGOING, TOTAL LIABILITY OF LSI FOR ANY REASON WHATSOEVER RELATED TO USE OF THE LSI SITE SHALL NOT EXCEED THE TOTAL AMOUNT PAID BY YOU TO LSI IN CONNECTION WITH THE USE OF THIS LSI SITE FOR THE PRIOR THREE MONTHS.
                  </li>
                  <li>
                    <b>INDEMNITY.</b> You agree to defend, indemnify, and hold harmless LSI and its affiliates, employees, agents, directors, officers, shareholders, attorneys, successors, and assigns from and against any and all claims, proceedings, damages, injuries, liabilities, losses, costs, and expenses (including reasonable attorneys' fees and litigation expenses) relating to or arising from any breach by You of this TOU. You acknowledge that any breach, threatened or actual, of this TOU may cause irreparable injury to LSI, such injury would not be quantifiable in monetary damages, and LSI would not have an adequate remedy at law. You therefore agree that LSI shall be entitled, in addition to other available remedies, to seek and be awarded an injunction or other appropriate equitable relief from a court of competent jurisdiction restraining any breach, threatened or actual, of Your obligations under any provision of this TOU.
                  </li>
                  <li>
                    <b>GOVERNING LAW.</b> This TOU has been made in and will be construed and enforced solely in accordance with the laws of the United States of America and the State of Tennessee, U.S.A. as applied to agreements entered into and completely performed in the State of Tennessee. You and LSI each agree to submit to exclusive subject matter jurisdiction, personal jurisdiction, and venue of the courts in Middle Tennessee in the State of Tennessee for any disputes between us under or arising out of this TOU. You also agree to waive any right to a jury trial in connection with any action or litigation in any way arising out of or related to this TOU and acknowledge that either party may seek attorney's fees in any proceeding. Any claim You might have against LSI must be brought within ONE (1) year after the cause of action arises, or such claim or cause of action is barred. You access the LSI Site on your own volition and are responsible for compliance with all applicable local laws with respect to Your access and use of the LSI Site.
                  </li>
                  <li>
                    <b>WAIVER, NO JOINT VENTURE, SEVERABILITY.</b> Failure by LSI to insist on strict performance of any of the terms and conditions of this TOU will not operate as a waiver by LSI of that or any subsequent default or failure of performance. If any provision (or part thereof) contained in this TOU is determined to be void, invalid, or otherwise unenforceable by a court of competent jurisdiction or on account of a conflict with an applicable government regulation, such determination shall not affect the remaining provisions (or parts thereof) contained herein and the illegal, invalid, or unenforceable clause shall be modified in compliance with applicable law in a manner that most closely matches the intent of the original language. No joint venture, partnership, employment, or agency relationship exists between You and LSI as result of this TOU or Your utilization of the LSI Site. Headings herein are for convenience only. This TOU shall be deemed to include all other notices, policies, disclaimers, and other terms contained in this LSI Site; provided, however, that in the event of a conflict between such other terms and these Terms, the terms contained herein shall control.
                  </li>
                  <li>
                    <b>THIRD PARTY PRODUCTS/SERVICES.</b> LSI, in its sole discretion, may post the advertisements of third parties on the LSI Site and/or feature materials, programs, products, and services provided by third parties, including, without limitation, LSI's members. LSI makes no representations with respect to the quality, non-infringement, accuracy, completeness, timeliness, reliability, or correct sequencing of such third party materials, programs, products, and services or any other materials, programs, products, and services which such third party materials, products, and services may access. Your correspondence or any other dealings with third parties found on the LSI Site are solely between You and such third party. Accordingly, LSI expressly disclaims responsibility and liability for all third party provided materials, programs, products, and services contained on or accessed through the LSI Site, and You agree that LSI shall not be responsible for any loss or damage of any sort incurred as a result of any such dealings or as the result of the presence of such third parties on the LSI Site.
                  </li>
                  <li>
                    <b>COPYRIGHT INFRINGEMENT NOTICE.</b> If you believe that Your work has been copied in a way that constitutes copyright infringement, or Your intellectual property rights have been otherwise violated, please follow our below Claims of Copyright Infringement Process and Requirements.
                  </li>
                </ol>
              </Col>
            </Row>
          </Container>
        </Container>
      </PageLayout>
      <Footer />
    </div>
  )
}